name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  nintendo-gba:
    name: Build (GBA, devkitARM)
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Install dependencies
        run: |
          # quickfix backports EOL
          rm /etc/apt/sources.list.d/bullseye-backports.list
          sudo apt-get update -qq
          sudo apt-get install -yqq ninja-build
          # quickfix broken option
          sudo sed "s/GRIT_NO_PAL)/GRIT_NO_PALETTE)/" -i ${DEVKITPRO}/cmake/dkp-gba-ds-utils.cmake

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Entombed
        run: |
          cmake -G Ninja -B build . -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build

      - name: Prepare artifact
        run: |
          cmake --build build --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: entombed-gba
          path: build/packages/*.*
